apiVersion: v1
kind: Namespace
metadata:
  name: squadlanes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: squadlanes-deployment
  namespace: squadlanes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: squadlanes
  template:
    metadata:
      labels:
        app: squadlanes
    spec:
      containers:
      - name: squadlanes
        image: ghcr.io/w4rum/squadlanes:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: github-registry
---
apiVersion: v1
kind: Service
metadata:
  name: squadlanes-service
  namespace: squadlanes
spec:
  selector:
    app: squadlanes
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: squadlanes-ingress
  namespace: squadlanes
  annotations:
      traefik.ingress.kubernetes.io/router.middlewares: default-https-redirect@kubernetescrd
      cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
      - squadlanes.com
      secretName: squadlanes-cert
  rules:
  - host: squadlanes.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: squadlanes-service
            port:
              number: 8080
